### ISSUE TITLE
No rerender after language change

### ISSUE THREAD

**Issue by ESalfinger** [Ghost---Shadow/i18nize-react#12]
Hey, great project! I have a problem that my components content only switches language after I refresh the page. 

I change my language by setting it in the local storage, correct?

```
const changeLanguage = lng => {
    localStorage.setItem("lng", lng);
  };
```

**Comment by Ghost---Shadow** [comment]
Yeah.

This tool is for automating out the boring parts of moving all the hardcoded text into a look up table. As an addition I added some "batteries included" features like Chinese and the language changer, but if you want to do it another way, you can!

**Comment by ESalfinger** [comment]
And how do i get the components to render in the new language after i set it in the localStorage?

**Comment by Ghost---Shadow** [comment]
In my application I just did a `window.reload()` in the callback of the language change button. You can do it in some other way.

**Comment by ESalfinger** [comment]
Works like a charm, thanks!
