### ISSUE TITLE
Feature Request: add support to typescript files

### ISSUE THREAD

**Issue by petrKoukal** [Ghost---Shadow/i18nize-react#2]
Would it be possible to add support to `.tsx` and `.ts` files?

As of now, when running the `i18nize-react` command on a React project developed in typescript, all the files are ignored. 

I see that in your `walker.js` file only `.jsx` and `js` files are considered for input. Chaning that to `.tsx` makes it partially work, but there are exceptions reported when parsing typescript files (e.g. when definining interfaces etc.)

**Comment by Ghost---Shadow** [comment]
Oh yeah. On it.

I will just whitelist `.ts` and `.tsx` files for now. Let me know if there are any other typescript specific issues you face.

**Comment by Ghost---Shadow** [comment]
`v0.10.0` published.

**Comment by Ghost---Shadow** [comment]
I will close this now. Let me know if you run into anything else.
