### ISSUE TITLE
useState issue

### ISSUE THREAD

**Issue by denis-n** [Ghost---Shadow/i18nize-react#7]
Hi,

thank you for your effort.

The project I'm working is using TypeScript and Prettier.

I did the dry run like you recommended and noticed that there are errors.

![image](https://user-images.githubusercontent.com/4423231/64262417-bb5b0980-cf36-11e9-86e6-ca3c2a6582b9.png)

The braces around curly braces `{}` are missing.
What can be done to fix this?

Thank you

**Comment by denis-n** [comment]
I found something mentioning `({})` in won't fix

https://github.com/Ghost---Shadow/i18nize-react/blob/master/wont-fix.md

**Comment by Ghost---Shadow** [comment]
[Redundant parenthesis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports) is indeed a false positive. 

But this is a genuine bug. I will look into it.

**Comment by denis-n** [comment]
Thank you

**Comment by Ghost---Shadow** [comment]
I have very little experience with typescript, but it looks like it is valid typescript syntax.

The bracket removal is not the consequence of any of my code. Babel is doing that for some reason.

![Capture](https://user-images.githubusercontent.com/7743925/64340345-8ec0f380-d003-11e9-86a3-51409c5a9ca5.PNG)

**Comment by Ghost---Shadow** [comment]
Until then use this regex :P
https://regex101.com/r/WbOTNk/1
