### ISSUE TITLE
Create a json file with all strings

### ISSUE THREAD

**Issue by denis-n** [Ghost---Shadow/i18nize-react#8]
Hi,

is it possible to only create one json file with all strings?
No need to support different languages.

Thank you

**Comment by Ghost---Shadow** [comment]
It is already creating one js file with all the strings. if you want to convert it into JSON you can string-ify it.

**Comment by denis-n** [comment]
How can I use it without `i18next`?

I want all my strings to come from database. So I was thinking if your tool can parse my project and instead of `i18n.t(k.LABEL)` can it be `k.LABEL`?)

**Comment by Ghost---Shadow** [comment]
Cant you do a find and replace?

https://regex101.com/r/dkh2d0/1

**Comment by denis-n** [comment]
I was just thinking that maybe there is a flag which does that.
