### ISSUE TITLE
i18nize didn't process all files.

### ISSUE THREAD

**Issue by denis-n** [Ghost---Shadow/i18nize-react#9]
Hi,

My React project is using TypeScript.

I noticed that not all `.tsx` files were processed by `i18nize-react`.

Are there any settings to force to do it?

Also, another thing is: how can we use `import `instead of `require `in generated files?

Mixing `import `and require `breaks `my app.

**Comment by Ghost---Shadow** [comment]
It should process `.tsx` files. It is white listed. (https://github.com/Ghost---Shadow/i18nize-react/blob/master/src/walker.js)

Mixing require and import breaks due to this line. (https://github.com/Ghost---Shadow/i18nize-react/blob/7c6b0a5baf2073ff07edc4c9a54719f4acd76df9/src/index.js#L69)

When I made this I was not aware of [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports)

**Comment by denis-n** [comment]
Yes, some `tsx` files are parsed, but some are not.

Can it be because of the directory level maybe?

**Comment by Ghost---Shadow** [comment]
It walks recursively to an unspecified depth.

These are the only ignore conditions along with ignoring `node_modules`
```
const checkIfFileShouldBeIgnored = (fullPath) => {
  const hasJsExtension = fullPath.trim().match(/\.[jt]sx?$/);
  const isTestFile = fullPath.trim().match(/(test.jsx?|spec.jsx?)/);

  return !(hasJsExtension && !isTestFile);
};
```

**Comment by denis-n** [comment]
Yeah, I noticed that it didn't skip the test files with `.ts` or `.tsx` extension.

**Comment by Ghost---Shadow** [comment]
I have very little experience with typescript, but it looks like it is valid typescript syntax.

The bracket removal is not the consequence of any of my code. Babel is doing that for some reason. 

![Capture](https://user-images.githubusercontent.com/7743925/64340210-3ee22c80-d003-11e9-877e-d64fcfc17a39.PNG)

**Comment by Ghost---Shadow** [comment]
I added skipping for typescript test files in `i18nize-react@0.11.0`

I need more info regarding what kind of filenames is it skipping.

The only place `require` is being used is here.

```js
// If running this script for the second time, it should not
// discard the table generated from the first run
if (fs.existsSync(path.join(path.resolve(inputDir), `${sourceDir}/i18n/english.js`))) {
  console.log('english.js exists');
  // eslint-disable-next-line
  const oldLut = require(path.join(path.resolve(inputDir), `${sourceDir}/i18n/english`));
  LutManager.setLut(oldLut);
}
```

If you are confident that you dont have to run the script a second time, you can just change the `require` to an `import`.

I hope that solves the problem.

**Comment by denis-n** [comment]
the test name looked like this: `App.test.tsx`, `index.test.tsx`.

Thank you for your work.
